[package]
name = "risc-bot"
version = "0.0.1"
authors = ["timvisee <timvisee@gmail.com>"]

[dependencies]
chrono = "0.4"
futures = "0.1"
htmlescape = "0.3"
lazy_static = "1.0"
regex = "1.0"
telegram-bot = "0.6"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-process = "0.2"
tokio-timer = "0.2"
