CREATE TABLE chat (
  telegram_id   BIGINT          PRIMARY KEY,
  title         VARCHAR(255)    NOT NULL,
  created_at    DATETIME        NOT NULL
    DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME        NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);
